# Generated by Django 3.2.9 on 2021-12-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211207_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.jpg', upload_to='thumbnail/'),
        ),
    ]
